### ISSUE TITLE
I/O error while reading marker byte: failed to fill full buffer

### ISSUE THREAD

**Issue by Nukesor** [daa84/neovim-lib#25] opened 2019-04-30 15:10 UTC
Hi!

First of all thanks for providing this plugin :).
I'm currently planning to write a rust reimplementation of the ctrlp.vim plugin.

While playing around with the library and trying to get a simple test setup working, I stumbled upon these nvim_error_events:

```
14:51:06 [INFO] ctrlp_rs::handler: [src/handler.rs:23] Incoming event: search
14:51:06 [INFO] ctrlp_rs: [src/main.rs:87] Waiting
14:51:06 [DEBUG] neovim_lib::rpc::client: [/home/nuke/.cargo/registry/src/github.com-1ecc6299db9ec823/neovim-lib-0.6.1/src/rpc/client.rs:242] Get message RpcNotification { method: "nvim_error_event", params: [Integer(PosInt(1)), String(Utf8String { s: Ok("Message is not an array") })] }
14:51:06 [INFO] ctrlp_rs::handler: [src/handler.rs:23] Incoming event: nvim_error_event
14:51:06 [ERROR] ctrlp_rs::handler: [src/handler.rs:36] Got nvim Error:
14:51:06 [ERROR] ctrlp_rs::handler: [src/handler.rs:37] [Integer(PosInt(1)), String(Utf8String { s: Ok("Message is not an array") })]
14:51:06 [ERROR] neovim_lib::rpc::client: [/home/nuke/.cargo/registry/src/github.com-1ecc6299db9ec823/neovim-lib-0.6.1/src/rpc/client.rs:237] Error while reading: I/O error while reading marker byte: failed to fill whole buffer
```

The rust bin is simply receiving events, and doesn't manipulate the Neovim instance and doesn't call any other functions on the Neovim instance.
I'm kind of confused, where these errors originate, maybe you can clarify things a little.

Project files:
https://github.com/Nukesor/ctrlp-rs.vim/blob/master/src/main.rs
https://github.com/Nukesor/ctrlp-rs.vim/blob/master/src/handler.rs

**Comment by boxofrox** [comment] 2019-04-30 19:52
Could you provide a list of steps to reproduce?

Also, since you continue to make changes, could you post which revision exhibited this behavior?  Your recent change to rename `ctrlp.vim` to `ctrlprs.vim` breaks the `init.vim` which still sources the old filename.

After correcting the filename in `init.vim`, I tried these steps.

```
# At shell prompt.
nvim -u init.vim

# In neovim v0.3.4.  Initialize ctrlp-rs.  The line after is an echoed result.
:call ctrlprs#init()
ctrlp error: stderr

# Check messages.
:message
ctrlp-rs: Started process
ctrlp error: stderrthread 'main' panicked at 'scorched earth: unable to initialize logger.: Os { code: 2, kind: NotFound, message: "No such file or directory"
}', src/libcore/result.rs:997:5^@note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
ctrlp error: stderr
```

I'm obviously missing something in order to reproduce your error, but I'm not sure what.

**Comment by KillTheMule** [comment] 2019-04-30 21:31
I've seen this error often, and always in the following 2 circumstances:

* A neovim misfeature (which limited message size to 10MB, fixed now to be 2GB)
* I made a mistake which made neovim hang up the channel

First, I'd look at the [log of a debug build](https://github.com/neovim/neovim/wiki/Development-tips#log-file-location) of neovim built with `MIN_LOG_LEVEL=0` to see if that tells you anything.

But I see in your case  there's an error in there that tells you that you sent something wrong. I could not perform a proper analysis now, but I'd BET that [`println!`](https://github.com/Nukesor/ctrlp-rs.vim/blob/8118d6a7d58d92b73d6a01c4c6786e2f07d675f3/src/main.rs#L88) wreaks havoc with running rpc over stdin/stdout (don't ask how often I've made that mistake).

**Comment by boxofrox** [comment] 2019-04-30 21:35
I can confirm the error reported disappears when the following patch to remove the only `println!()` is applied.

```diff
diff --git a/src/main.rs b/src/main.rs
index 33e24fd..2044f44 100644
--- a/src/main.rs
+++ b/src/main.rs
@@ -85,7 +85,6 @@ fn start_event_loop(receiver: mpsc::Receiver<Event>, mut nvim: Neovim) {
     loop {
         info!("Waiting");
         let payload = receiver.recv();
-        println!("Received Payload: {:?}", payload);
         match payload {
             Ok(Event::Shutdown) => {
                 info!("Shutting down");
```

**Comment by Nukesor** [comment] 2019-05-03 11:45
Of course. I completely forgot that rpc communication happens via stdout/stdin.
Removing the println! indeed resolved this bug. I kind of feel stupid about this one.
Sorry for causing you any inconvenience and thanks for helping and for providing this library!

**Closed** 2019-05-03 11:52 UTC
